### ISSUE TITLE
Module Error 

### ISSUE THREAD

**Issue by yusiqo** [thehamkercat/WilliamButcherBot#218]
AttributeError: module 'httpcore' has no attribute 'NetworkBackend'

**Comment by TheHamkerCat** [comment]
Are you deploying with docker?

**Comment by yusiqo** [comment]
l solved this error but. new error..

untimeError: Event loop is closed
Task was destroyed but it is pending!

**Comment by OKiU-Network** [comment]
Got same issue here:
`Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/wbb/wbb/__init__.py", line 30, in <module>
    from motor.motor_asyncio import AsyncIOMotorClient as MongoClient
  File "/usr/local/lib/python3.9/site-packages/motor/motor_asyncio.py", line 18, in <module>
    from . import core, motor_gridfs
  File "/usr/local/lib/python3.9/site-packages/motor/core.py", line 21, in <module>
    import pymongo
  File "/usr/local/lib/python3.9/site-packages/pymongo/__init__.py", line 92, in <module>
    from pymongo.mongo_client import MongoClient
  File "/usr/local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 66, in <module>
    from pymongo import (
  File "/usr/local/lib/python3.9/site-packages/pymongo/uri_parser.py", line 46, in <module>
    from pymongo.srv_resolver import _HAVE_DNSPYTHON, _SrvResolver
  File "/usr/local/lib/python3.9/site-packages/pymongo/srv_resolver.py", line 23, in <module>
    from dns import resolver
  File "/usr/local/lib/python3.9/site-packages/dns/resolver.py", line 30, in <module>
    import dns._ddr
  File "/usr/local/lib/python3.9/site-packages/dns/_ddr.py", line 12, in <module>
    import dns.nameserver
  File "/usr/local/lib/python3.9/site-packages/dns/nameserver.py", line 5, in <module>
    import dns.asyncquery
  File "/usr/local/lib/python3.9/site-packages/dns/asyncquery.py", line 38, in <module>
    from dns.query import (
  File "/usr/local/lib/python3.9/site-packages/dns/query.py", line 67, in <module>
    _CoreNetworkBackend = httpcore.NetworkBackend
AttributeError: module 'httpcore' has no attribute 'NetworkBackend'
`

**Comment by si-nn-er-ls** [comment]
> Got same issue here: `Traceback (most recent call last): File "/usr/local/lib/python3.9/runpy.py", line 188, in _run_module_as_main mod_name, mod_spec, code = _get_module_details(mod_name, _Error) File "/usr/local/lib/python3.9/runpy.py", line 147, in _get_module_details return _get_module_details(pkg_main_name, error) File "/usr/local/lib/python3.9/runpy.py", line 111, in _get_module_details __import__(pkg_name) File "/wbb/wbb/__init__.py", line 30, in <module> from motor.motor_asyncio import AsyncIOMotorClient as MongoClient File "/usr/local/lib/python3.9/site-packages/motor/motor_asyncio.py", line 18, in <module> from . import core, motor_gridfs File "/usr/local/lib/python3.9/site-packages/motor/core.py", line 21, in <module> import pymongo File "/usr/local/lib/python3.9/site-packages/pymongo/__init__.py", line 92, in <module> from pymongo.mongo_client import MongoClient File "/usr/local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 66, in <module> from pymongo import ( File "/usr/local/lib/python3.9/site-packages/pymongo/uri_parser.py", line 46, in <module> from pymongo.srv_resolver import _HAVE_DNSPYTHON, _SrvResolver File "/usr/local/lib/python3.9/site-packages/pymongo/srv_resolver.py", line 23, in <module> from dns import resolver File "/usr/local/lib/python3.9/site-packages/dns/resolver.py", line 30, in <module> import dns._ddr File "/usr/local/lib/python3.9/site-packages/dns/_ddr.py", line 12, in <module> import dns.nameserver File "/usr/local/lib/python3.9/site-packages/dns/nameserver.py", line 5, in <module> import dns.asyncquery File "/usr/local/lib/python3.9/site-packages/dns/asyncquery.py", line 38, in <module> from dns.query import ( File "/usr/local/lib/python3.9/site-packages/dns/query.py", line 67, in <module> _CoreNetworkBackend = httpcore.NetworkBackend AttributeError: module 'httpcore' has no attribute 'NetworkBackend' `

https://github.com/TheHamkerCat/WilliamButcherBot/pull/220/commits/f29daaf093e47e20ab00b274f1fcdd45c7926a54
